# Generated by Django 4.2.13 on 2024-06-13 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='대분류이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'main_category',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='가맹점이름')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='가맹점연락처')),
                ('representative', models.CharField(max_length=20, null=True, verbose_name='대표자이름')),
                ('zipcode', models.CharField(default='', max_length=10, verbose_name='우편번호')),
                ('address', models.CharField(default='', max_length=255, verbose_name='주소')),
                ('address_detail', models.CharField(default='', max_length=255, verbose_name='상세주소')),
                ('registration_no', models.CharField(max_length=20, null=True, verbose_name='가맹점사업자등록번호')),
                ('image', models.ImageField(max_length=300, null=True, upload_to='image/shop/', verbose_name='가맹점이미지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='소분류이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_category', to='system_manage.maincategory')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='ShopAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shop_admin',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membername', models.CharField(default='', max_length=50, verbose_name='회원명')),
                ('phone', models.CharField(default='', max_length=30, verbose_name='전화번호')),
                ('gender', models.CharField(default='M', max_length=10, verbose_name='성별')),
                ('birth', models.DateField(verbose_name='생년월일')),
                ('zipcode', models.CharField(default='', max_length=10, verbose_name='우편번호')),
                ('address', models.CharField(default='', max_length=255, verbose_name='주소')),
                ('address_detail', models.CharField(default='', max_length=255, verbose_name='상세주소')),
                ('withdrawal_at', models.DateTimeField(null=True, verbose_name='탈퇴일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_profile',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='제품가격')),
                ('image', models.ImageField(max_length=300, upload_to='image/goods/%Y/%m/%d/', verbose_name='상품이미지')),
                ('image_thumbnail', models.ImageField(max_length=300, upload_to='image/goods/%Y/%m/%d/', verbose_name='상품이미지 썸네일 정사각형')),
                ('sold_out', models.BooleanField(default=False, verbose_name='품절관리')),
                ('delete_flag', models.BooleanField(default=False, verbose_name='삭제처리')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shop')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system_manage.subcategory')),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('main_category', 'name'), name='main_category_name_unique'),
        ),
    ]
