# Generated by Django 4.2.13 on 2024-06-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(default='1990-01-01', verbose_name='생년월일'),
        ),
        migrations.AddConstraint(
            model_name='shopadmin',
            constraint=models.UniqueConstraint(fields=('shop', 'user'), name='shop_user_unique'),
        ),
    ]
