# Generated by Django 4.2.13 on 2024-06-14 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system_manage', '0002_shop_description_alter_profile_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='sold_out',
        ),
        migrations.AddField(
            model_name='goods',
            name='status',
            field=models.BooleanField(default=True, verbose_name='판매상태'),
        ),
        migrations.AlterField(
            model_name='shopadmin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
