# Generated by Django 4.2.13 on 2024-06-14 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0006_alter_entryqueue_membername_alter_entryqueue_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                (
                    "final_price",
                    models.PositiveIntegerField(default=0, verbose_name="최종결제금액"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.shop",
                    ),
                ),
            ],
            options={
                "db_table": "checkout",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_name",
                    models.CharField(max_length=255, null=True, verbose_name="주문명"),
                ),
                ("order_code", models.CharField(max_length=20, verbose_name="주문번호")),
                (
                    "status",
                    models.CharField(default="0", max_length=10, verbose_name="결제상태"),
                ),
                (
                    "final_price",
                    models.PositiveIntegerField(default=0, verbose_name="최종결제요청금액"),
                ),
                (
                    "payment_price",
                    models.PositiveIntegerField(default=0, verbose_name="실제결제금액"),
                ),
                (
                    "payment_method",
                    models.CharField(default="", max_length=10, verbose_name="결제수단"),
                ),
                ("cancelled_at", models.DateTimeField(null=True, verbose_name="취소일")),
                ("date", models.DateField(auto_now_add=True, verbose_name="날짜")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "delete_flag",
                    models.BooleanField(default=False, verbose_name="삭제여부"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.shop",
                    ),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
        migrations.AddField(
            model_name="entryqueue",
            name="status",
            field=models.CharField(default="0", max_length=10, verbose_name="상태"),
        ),
        migrations.AlterField(
            model_name="shopentrygoods",
            name="goods",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_goods",
                to="system_manage.goods",
            ),
        ),
        migrations.CreateModel(
            name="OrderGoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, null=True, verbose_name="제품명"),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="가격")),
                (
                    "total_price",
                    models.PositiveIntegerField(default=0, verbose_name="총가격"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="주문수량"),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_goods",
                        to="system_manage.goods",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_goods",
                        to="system_manage.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_goods",
            },
        ),
        migrations.CreateModel(
            name="CheckoutDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="수량")),
                ("price", models.PositiveIntegerField(verbose_name="가격")),
                ("total_price", models.PositiveIntegerField(verbose_name="총가격")),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_detail",
                        to="system_manage.checkout",
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.goods",
                    ),
                ),
            ],
            options={
                "db_table": "checkout_detail",
            },
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("shop", "order_code"), name="shop_order_code_unique"
            ),
        ),
    ]
