# Generated by Django 4.2.13 on 2024-06-15 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0008_order_order_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodsOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField(default=True, verbose_name="필수여부")),
                ("name", models.CharField(max_length=100, verbose_name="옵션명")),
            ],
            options={
                "db_table": "goods_option",
            },
        ),
        migrations.AddField(
            model_name="goods",
            name="option_flag",
            field=models.BooleanField(default=False, verbose_name="옵션여부관리"),
        ),
        migrations.AddField(
            model_name="goods",
            name="soldout",
            field=models.BooleanField(default=False, verbose_name="품절"),
        ),
        migrations.AddField(
            model_name="goods",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="재고수량"),
        ),
        migrations.AddField(
            model_name="goods",
            name="stock_flag",
            field=models.BooleanField(default=False, verbose_name="재고여부관리"),
        ),
        migrations.CreateModel(
            name="GoodsOptionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="옵션명")),
                ("price", models.PositiveIntegerField(default=0, verbose_name="옵션가격")),
                ("stock", models.IntegerField(default=0, verbose_name="재고수량")),
                (
                    "goods_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_detail",
                        to="system_manage.goodsoption",
                    ),
                ),
            ],
            options={
                "db_table": "product_option_detail",
            },
        ),
        migrations.AddField(
            model_name="goodsoption",
            name="goods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goods",
                to="system_manage.goods",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsoption",
            constraint=models.UniqueConstraint(
                fields=("goods", "name"), name="goods_name_unique"
            ),
        ),
    ]
