# Generated by Django 4.2.13 on 2024-06-15 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0009_goodsoption_goods_option_flag_goods_soldout_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShopEntryGoods",
        ),
    ]
