# Generated by Django 4.2.13 on 2024-06-15 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0010_delete_shopentrygoods"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="goodsoptiondetail",
            table="goods_option_detail",
        ),
    ]
