# Generated by Django 4.2.13 on 2024-06-16 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0011_alter_goodsoptiondetail_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="option_flag",
            field=models.BooleanField(default=False, verbose_name="옵션사용여부"),
        ),
        migrations.AlterField(
            model_name="goods",
            name="stock_flag",
            field=models.BooleanField(default=False, verbose_name="재고관리사용여부"),
        ),
        migrations.AlterField(
            model_name="goodsoption",
            name="goods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option",
                to="system_manage.goods",
            ),
        ),
    ]
