# Generated by Django 4.2.13 on 2024-06-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system_manage",
            "0012_alter_goods_option_flag_alter_goods_stock_flag_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="sale_price",
            field=models.PositiveIntegerField(default=0, verbose_name="판매가격"),
        ),
    ]
