# Generated by Django 4.2.13 on 2024-06-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0013_goods_sale_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="agency이름"
                    ),
                ),
                (
                    "description",
                    models.CharField(default="", max_length=255, verbose_name="설명"),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=300,
                        null=True,
                        upload_to="image/agency/",
                        verbose_name="에이전시이미지",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="상태")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "db_table": "agency",
            },
        ),
        migrations.CreateModel(
            name="AgencyShop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=True, verbose_name="상태")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agnecy_shop",
                        to="system_manage.agency",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.shop",
                    ),
                ),
            ],
            options={
                "db_table": "agency_shop",
            },
        ),
        migrations.AddConstraint(
            model_name="agencyshop",
            constraint=models.UniqueConstraint(
                fields=("agency", "shop"), name="agency_shop_unique"
            ),
        ),
    ]
