# Generated by Django 4.2.13 on 2024-06-17 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0015_alter_agencyshop_agency"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutDetailOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checkout_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_detail_option",
                        to="system_manage.checkoutdetail",
                    ),
                ),
                (
                    "goods_option_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.goodsoptiondetail",
                    ),
                ),
            ],
            options={
                "db_table": "checkout_detail_option",
            },
        ),
    ]
