# Generated by Django 4.2.13 on 2024-06-18 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0016_checkoutdetailoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="agency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="system_manage.agency",
            ),
        ),
    ]
