# Generated by Django 4.2.13 on 2024-06-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0018_ordergoods_option_ordergoods_option_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(max_length=50, verbose_name="주문번호"),
        ),
    ]
