# Generated by Django 4.2.13 on 2024-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0019_alter_order_order_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergoods",
            name="option",
            field=models.CharField(max_length=255, null=True, verbose_name="옵션"),
        ),
    ]
