# Generated by Django 4.2.13 on 2024-06-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0021_order_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsoptiondetail",
            name="stock_flag",
            field=models.BooleanField(default=False, verbose_name="재고관리사용여부"),
        ),
    ]
