# Generated by Django 4.2.13 on 2024-06-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0022_goodsoptiondetail_stock_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_membername",
            field=models.CharField(default="", max_length=20, verbose_name="주문자명"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_no",
            field=models.PositiveIntegerField(default=0, verbose_name="주문번호"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(max_length=50, verbose_name="주문코드"),
        ),
    ]
