# Generated by Django 4.2.13 on 2024-06-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0023_order_order_membername_order_order_no_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("shop", "order_no", "date"), name="shop_order_no_date_unique"
            ),
        ),
    ]
