# Generated by Django 4.2.13 on 2024-06-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0024_order_shop_order_no_date_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="가맹점카테고리이름"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=300,
                        null=True,
                        upload_to="image/shop_category/",
                        verbose_name="가맹점카테고리이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "db_table": "shop_category",
            },
        ),
    ]
