# Generated by Django 4.2.13 on 2024-06-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0025_shopcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="system_manage.shopcategory",
            ),
        ),
    ]
