# Generated by Django 4.2.13 on 2024-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0026_shop_shop_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopcategory",
            name="description",
            field=models.CharField(default="", max_length=255, verbose_name="설명"),
        ),
    ]
