# Generated by Django 4.2.13 on 2024-06-20 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0027_shopcategory_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsoptiondetail",
            name="soldout",
            field=models.BooleanField(default=False, verbose_name="품절 여부"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="shop_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shop",
                to="system_manage.shopcategory",
            ),
        ),
    ]
