# Generated by Django 4.2.13 on 2024-06-21 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0029_ordergoodsoption"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordergoodsoption",
            old_name="checkout_detail",
            new_name="order_goods",
        ),
    ]
