# Generated by Django 4.2.13 on 2024-06-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0032_alter_ordergoodsoption_order_goods"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refNo",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="cardAmount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="couponAmount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="order",
            name="pointAmount",
            field=models.IntegerField(default=0),
        ),
    ]
