# Generated by Django 4.2.13 on 2024-06-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0033_order_refno_alter_order_cardamount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_complete_sms",
            field=models.BooleanField(default=False, verbose_name="주문완료문자"),
        ),
    ]
