# Generated by Django 4.2.13 on 2024-07-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0034_order_order_complete_sms"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopEntryPersonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="사람타입")),
                (
                    "description",
                    models.CharField(default="", max_length=255, verbose_name="설명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.shop",
                    ),
                ),
            ],
            options={
                "db_table": "shop_entry_person_type",
            },
        ),
        migrations.AddConstraint(
            model_name="shopentrypersontype",
            constraint=models.UniqueConstraint(
                fields=("shop", "name"), name="shop_name_unique"
            ),
        ),
    ]
