# Generated by Django 4.2.13 on 2024-07-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0035_shopentrypersontype_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="사람타입"),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=300,
                        null=True,
                        upload_to="image/person_type/",
                        verbose_name="사람이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "db_table": "person_type",
            },
        ),
    ]
