# Generated by Django 4.2.13 on 2024-07-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0036_persontype"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopPersonType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(default="", max_length=255, verbose_name="설명"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "person_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.persontype",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.shop",
                    ),
                ),
            ],
            options={
                "db_table": "shop_person_type",
            },
        ),
        migrations.DeleteModel(
            name="ShopEntryPersonType",
        ),
        migrations.AddConstraint(
            model_name="shoppersontype",
            constraint=models.UniqueConstraint(
                fields=("shop", "person_type"), name="shop_person_type_unique"
            ),
        ),
    ]
