# Generated by Django 4.2.13 on 2024-07-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0038_shoptable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoptable",
            name="name",
            field=models.CharField(max_length=100, verbose_name="테이블명"),
        ),
    ]
