# Generated by Django 4.2.13 on 2024-07-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0040_shoptable_table_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoptable",
            name="table_no",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="shoptable",
            constraint=models.UniqueConstraint(
                fields=("shop", "table_no"), name="shop_table_no_unique"
            ),
        ),
    ]
