# Generated by Django 4.2.13 on 2024-07-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0042_shoppersontype_goods"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="entry_car_plate_no",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shop",
            name="entry_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shop",
            name="entry_membername",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shop",
            name="entry_phone",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shoptable",
            name="cart",
            field=models.TextField(null=True, verbose_name="장바구니"),
        ),
    ]
