# Generated by Django 4.2.13 on 2024-07-09 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0043_shop_entry_car_plate_no_shop_entry_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopEntryOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required", models.BooleanField(default=True, verbose_name="필수여부")),
                ("name", models.CharField(max_length=100, verbose_name="옵션명")),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_option",
                        to="system_manage.shop",
                    ),
                ),
            ],
            options={
                "db_table": "shop_entry_option",
            },
        ),
        migrations.CreateModel(
            name="ShopEntryOptionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="옵션명")),
                (
                    "image",
                    models.ImageField(
                        max_length=300,
                        upload_to="image/shop_entry_option/%Y/%m/%d/",
                        verbose_name="옵션이미지",
                    ),
                ),
                (
                    "image_thumbnail",
                    models.ImageField(
                        max_length=300,
                        upload_to="image/shop_entry_option/%Y/%m/%d/",
                        verbose_name="옵션 이미지 썸네일 정사각형",
                    ),
                ),
                (
                    "shop_entry_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_option_detail",
                        to="system_manage.shopentryoption",
                    ),
                ),
            ],
            options={
                "db_table": "shop_entry_option_detail",
            },
        ),
        migrations.AddConstraint(
            model_name="shopentryoption",
            constraint=models.UniqueConstraint(
                fields=("shop", "name"), name="shop_name_unique"
            ),
        ),
    ]
