# Generated by Django 4.2.13 on 2024-07-09 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0044_shopentryoption_shopentryoptiondetail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryqueue",
            name="email",
            field=models.CharField(default="", max_length=50, verbose_name="이메일"),
        ),
        migrations.AddField(
            model_name="shoptable",
            name="entry_time",
            field=models.DateTimeField(null=True, verbose_name="입장시간"),
        ),
        migrations.CreateModel(
            name="ShopTableLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "shop_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.shoptable",
                    ),
                ),
            ],
            options={
                "db_table": "shop_table_log",
            },
        ),
        migrations.CreateModel(
            name="ShopMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "membername",
                    models.CharField(default="", max_length=50, verbose_name="회원명"),
                ),
                (
                    "phone",
                    models.CharField(default="", max_length=30, verbose_name="전화번호"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.shop",
                    ),
                ),
            ],
            options={
                "db_table": "shop_member",
            },
        ),
        migrations.AddField(
            model_name="shoptable",
            name="shop_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system_manage.shopmember",
            ),
        ),
    ]
