# Generated by Django 4.2.13 on 2024-07-09 15:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "system_manage",
            "0045_entryqueue_email_shoptable_entry_time_shoptablelog_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopentryoptiondetail",
            name="image_thumbnail",
        ),
    ]
