# Generated by Django 4.2.13 on 2024-07-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0047_shop_agency_alter_shopentryoptiondetail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shop",
                to="system_manage.agency",
                verbose_name="메인 agency",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="shop_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shop",
                to="system_manage.shopcategory",
            ),
        ),
    ]
