# Generated by Django 4.2.13 on 2024-07-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0050_profile_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="entry_image",
            field=models.ImageField(
                max_length=300,
                null=True,
                upload_to="image/shop_entry/",
                verbose_name="가맹점 입장",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="logo",
            field=models.ImageField(
                max_length=300,
                null=True,
                upload_to="image/shop_logo/",
                verbose_name="가맹점 로고이미지",
            ),
        ),
    ]
