# Generated by Django 4.2.13 on 2024-07-10 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0051_shop_entry_image_shop_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="logo",
            new_name="logo_image",
        ),
    ]
