# Generated by Django 4.2.13 on 2024-07-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0053_entryqueue_remark_entryqueue_shop_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shop_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system_manage.shopmember",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="table_no",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
