# Generated by Django 4.2.13 on 2024-07-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0054_order_shop_member_order_table_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryqueuedetail",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="entryqueuedetail",
            name="goods",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system_manage.goods",
            ),
        ),
    ]
