# Generated by Django 4.2.13 on 2024-07-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0055_entryqueuedetail_name_alter_entryqueuedetail_goods"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entryqueuedetail",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
