# Generated by Django 4.2.13 on 2024-07-10 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0056_alter_entryqueuedetail_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoptablelog",
            name="shop_member",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system_manage.shopmember",
            ),
        ),
    ]
