# Generated by Django 4.2.13 on 2024-07-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0057_shoptablelog_shop_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoptable",
            name="total_price",
            field=models.PositiveIntegerField(default=0, verbose_name="총 결제 금액"),
        ),
    ]
