# Generated by Django 4.2.13 on 2024-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0059_rename_entry_image_shop_entry_image1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="entry_image2",
            field=models.ImageField(
                max_length=300,
                null=True,
                upload_to="image/shop_entry/",
                verbose_name="가맹점 입장이미지2",
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="logo_image2",
            field=models.ImageField(
                max_length=300,
                null=True,
                upload_to="image/shop_logo/",
                verbose_name="가맹점 로고이미지2",
            ),
        ),
    ]
