# Generated by Django 4.2.13 on 2024-07-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0060_shop_entry_image2_shop_logo_image2"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="waiting_time",
            field=models.PositiveIntegerField(default=10, verbose_name="팀 당 예상 대기시간"),
        ),
    ]
