# Generated by Django 4.2.13 on 2024-07-13 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0061_shop_waiting_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entryqueuedetail",
            name="entry_queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_queue_detail",
                to="system_manage.entryqueue",
            ),
        ),
    ]
