# Generated by Django 4.2.13 on 2024-07-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0064_checkout_shop_member_checkout_table_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(default="0", max_length=10, verbose_name="주문방식"),
        ),
    ]
