# Generated by Django 4.2.13 on 2024-07-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0065_order_order_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="final_discount",
            field=models.PositiveIntegerField(default=0, verbose_name="최종 할인 금액"),
        ),
        migrations.AddField(
            model_name="checkoutdetail",
            name="discount",
            field=models.PositiveIntegerField(default=0, verbose_name="할인 가격"),
        ),
        migrations.AddField(
            model_name="order",
            name="final_discount",
            field=models.PositiveIntegerField(default=0, verbose_name="최종 할인 금액"),
        ),
        migrations.AddField(
            model_name="shoptable",
            name="total_discount",
            field=models.PositiveIntegerField(default=0, verbose_name="총 할인 금액"),
        ),
    ]
