# Generated by Django 4.2.13 on 2024-07-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0071_remove_goods_name_alter_goods_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergoods",
            name="name_en",
            field=models.CharField(max_length=255, null=True, verbose_name="제품한글명"),
        ),
        migrations.AddField(
            model_name="ordergoods",
            name="name_kr",
            field=models.CharField(max_length=255, null=True, verbose_name="제품영어명"),
        ),
    ]
