# Generated by Django 4.2.13 on 2024-07-25 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0072_ordergoods_name_en_ordergoods_name_kr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordergoods",
            name="name",
        ),
    ]
