# Generated by Django 4.2.13 on 2024-07-25 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0074_order_order_name_en_order_order_name_kr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_name",
        ),
    ]
