# Generated by Django 4.2.13 on 2024-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0075_remove_order_order_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsoption",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="옵션영문명"),
        ),
        migrations.AddField(
            model_name="goodsoption",
            name="name_kr",
            field=models.CharField(max_length=100, null=True, verbose_name="옵션한글명"),
        ),
        migrations.AddField(
            model_name="goodsoptiondetail",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="옵션영문명"),
        ),
        migrations.AddField(
            model_name="goodsoptiondetail",
            name="name_kr",
            field=models.CharField(max_length=100, null=True, verbose_name="옵션한글명"),
        ),
    ]
