# Generated by Django 4.2.13 on 2024-07-25 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0076_goodsoption_name_en_goodsoption_name_kr_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="goodsoption",
            name="goods_name_unique",
        ),
    ]
