# Generated by Django 4.2.13 on 2024-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0079_remove_goodsoptiondetail_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergoods",
            name="option_en",
            field=models.CharField(max_length=255, null=True, verbose_name="옵션영문명"),
        ),
        migrations.AddField(
            model_name="ordergoods",
            name="option_kr",
            field=models.CharField(max_length=255, null=True, verbose_name="옵션한글명"),
        ),
    ]
