# Generated by Django 4.2.13 on 2024-07-25 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0080_ordergoods_option_en_ordergoods_option_kr"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordergoods",
            name="option",
        ),
    ]
