# Generated by Django 4.2.13 on 2024-07-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0084_maincategory_name_en_maincategory_name_kr_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subcategory",
            name="main_category_name_unique",
        ),
        migrations.RemoveField(
            model_name="maincategory",
            name="name",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="name",
        ),
        migrations.AlterField(
            model_name="maincategory",
            name="name_en",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="대분류 영문이름"
            ),
        ),
        migrations.AlterField(
            model_name="maincategory",
            name="name_kr",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="대분류 한글이름"
            ),
        ),
    ]
