# Generated by Django 4.2.13 on 2024-07-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0085_remove_subcategory_main_category_name_unique_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("main_category", "name_kr"), name="main_category_name_kr_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("main_category", "name_en"), name="main_category_name_en_unique"
            ),
        ),
    ]
