# Generated by Django 4.2.13 on 2024-07-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0086_subcategory_main_category_name_kr_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoptable",
            name="table_no",
            field=models.IntegerField(),
        ),
    ]
