# Generated by Django 4.2.13 on 2024-07-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0087_alter_shoptable_table_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkout",
            name="table_no",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="table_no",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
