# Generated by Django 4.2.13 on 2024-07-25 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0088_alter_checkout_table_no_alter_order_table_no"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("refNo", models.CharField(default="", max_length=20)),
                ("mbrNo", models.CharField(default="", max_length=20)),
                ("mbrRefNo", models.CharField(default="", max_length=100)),
                ("tranDate", models.CharField(default="", max_length=20)),
                ("tranTime", models.CharField(default="", max_length=20)),
                ("goodsName", models.CharField(default="", max_length=100)),
                ("amount", models.IntegerField(default=0)),
                ("taxAmount", models.IntegerField(default=0)),
                ("feeAmount", models.IntegerField(default=0)),
                ("taxFreeAmount", models.IntegerField(default=0)),
                ("greenDepositAmount", models.IntegerField(default=0)),
                ("installment", models.CharField(default="", max_length=20)),
                ("custormerName", models.CharField(default="", max_length=50)),
                ("customerTelNo", models.CharField(default="", max_length=20)),
                ("applNo", models.CharField(default="", max_length=20)),
                ("cardNo", models.CharField(default="", max_length=100)),
                ("issueCompanyNo", models.CharField(default="", max_length=10)),
                ("issueCompanyName", models.CharField(default="", max_length=20)),
                ("issueCardName", models.CharField(default="", max_length=20)),
                ("acqCompanyNo", models.CharField(default="", max_length=20)),
                ("acqCompanyName", models.CharField(default="", max_length=20)),
                ("payType", models.CharField(default="", max_length=10)),
                ("cardAmount", models.IntegerField(default=0)),
                ("pointAmount", models.IntegerField(default=0)),
                ("couponAmount", models.IntegerField(default=0)),
                ("custormmerName", models.CharField(default="", max_length=50)),
                ("custormmerTelNo", models.CharField(default="", max_length=50)),
                ("cardPointAmount", models.IntegerField(default=0)),
                ("cardPointApplNo", models.CharField(default="", max_length=20)),
                ("bankCode", models.CharField(max_length=20, null=True)),
                ("accountNo", models.CharField(max_length=20, null=True)),
                ("accountCloseDate", models.CharField(max_length=20, null=True)),
                ("billkey", models.CharField(max_length=20, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_payment",
                        to="system_manage.order",
                    ),
                ),
            ],
            options={
                "db_table": "order_payment",
            },
        ),
    ]
