# Generated by Django 4.2.13 on 2024-07-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0089_orderpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopMemberCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_type",
                    models.CharField(default="0", max_length=10, verbose_name="쿠폰타입"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="쿠폰명")),
                (
                    "discount_type",
                    models.CharField(default="0", max_length=10, verbose_name="할인"),
                ),
                ("discount", models.PositiveIntegerField(default=0, verbose_name="할인")),
                ("status", models.CharField(default="0", max_length=10)),
                ("expiration_date", models.DateTimeField(verbose_name="만료일")),
                ("used_at", models.DateTimeField(null=True, verbose_name="사용일")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "shop_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shop_member_coupon",
                        to="system_manage.shopmember",
                    ),
                ),
            ],
            options={
                "db_table": "shop_member_coupon",
            },
        ),
        migrations.CreateModel(
            name="ShopCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "coupon_type",
                    models.CharField(default="0", max_length=10, verbose_name="쿠폰타입"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="쿠폰명")),
                (
                    "discount_type",
                    models.CharField(default="0", max_length=10, verbose_name="할인"),
                ),
                ("discount", models.PositiveIntegerField(default=0, verbose_name="할인")),
                (
                    "expiration_period",
                    models.PositiveIntegerField(default=365, verbose_name="유효기간"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "shop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system_manage.shop",
                    ),
                ),
            ],
            options={
                "db_table": "shop_coupon",
            },
        ),
    ]
