# Generated by Django 4.2.13 on 2024-07-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system_manage",
            "0091_remove_order_accountclosedate_remove_order_accountno_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="additionalInfo",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="approvalDate",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="approvalNumber",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="cardType",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="maskingCardNumber",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="posEntryMode",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="tid",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="cardNo",
            field=models.CharField(default="", max_length=50),
        ),
    ]
