# Generated by Django 4.2.13 on 2024-07-31 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0092_orderpayment_additionalinfo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderpayment",
            name="cardType",
        ),
    ]
