# Generated by Django 4.2.13 on 2024-07-31 17:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0093_remove_orderpayment_cardtype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderpayment",
            old_name="custormerName",
            new_name="customerName",
        ),
    ]
