# Generated by Django 4.2.13 on 2024-08-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0094_rename_custormername_orderpayment_customername"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="main_tid",
            field=models.CharField(default="", max_length=20, verbose_name="메인 tid"),
        ),
        migrations.AddField(
            model_name="shoptable",
            name="tid",
            field=models.CharField(default="", max_length=20, verbose_name="tid"),
        ),
    ]
