# Generated by Django 4.2.13 on 2024-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0095_shop_main_tid_shoptable_tid"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="final_additional",
            field=models.PositiveIntegerField(default=0, verbose_name="총 추가 금액"),
        ),
        migrations.AddField(
            model_name="order",
            name="final_additional",
            field=models.PositiveIntegerField(default=0, verbose_name="총 추가 금액"),
        ),
        migrations.AddField(
            model_name="shoptable",
            name="total_additional",
            field=models.PositiveIntegerField(default=0, verbose_name="총 추가 금액"),
        ),
    ]
