# Generated by Django 4.2.13 on 2024-08-01 16:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0097_remove_order_cancelled_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderpayment",
            name="approvalDate",
        ),
        migrations.RemoveField(
            model_name="orderpayment",
            name="maskingCardNumber",
        ),
    ]
