# Generated by Django 4.2.13 on 2024-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0098_remove_orderpayment_approvaldate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="status",
            field=models.BooleanField(default=True, verbose_name="결제여부"),
        ),
    ]
