# Generated by Django 4.2.13 on 2024-08-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0101_alter_orderpayment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="", max_length=20, verbose_name="결제수단"),
        ),
    ]
