# Generated by Django 4.2.13 on 2024-08-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0102_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="", max_length=10, verbose_name="결제수단"),
        ),
    ]
