# Generated by Django 4.2.13 on 2024-08-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0103_alter_order_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutdetail",
            name="sale_option_price",
            field=models.PositiveIntegerField(default=0, verbose_name="당시옵션판매가격"),
        ),
        migrations.AddField(
            model_name="checkoutdetail",
            name="sale_price",
            field=models.PositiveIntegerField(default=0, verbose_name="당시상품판매가격"),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="final_discount",
            field=models.PositiveIntegerField(default=0, verbose_name="전체 할인 금액"),
        ),
    ]
