# Generated by Django 4.2.13 on 2024-08-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0106_alter_ordergoods_sale_option_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkoutdetail",
            name="sale_option_price",
            field=models.PositiveIntegerField(verbose_name="당시옵션판매가격"),
        ),
        migrations.AlterField(
            model_name="checkoutdetail",
            name="sale_price",
            field=models.PositiveIntegerField(verbose_name="당시상품판매가격"),
        ),
    ]
