# Generated by Django 4.2.13 on 2024-08-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0107_alter_checkoutdetail_sale_option_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="cancelled_at",
            field=models.DateTimeField(null=True, verbose_name="취소일"),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="생성일"
            ),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="수정일"),
        ),
    ]
