# Generated by Django 4.2.13 on 2024-08-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system_manage",
            "0108_orderpayment_cancelled_at_orderpayment_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpayment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일"),
        ),
    ]
