# Generated by Django 4.2.13 on 2024-08-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0110_shop_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="receipt",
            field=models.CharField(default="", max_length=255, verbose_name="영수증내용"),
        ),
    ]
