# Generated by Django 4.2.13 on 2024-08-06 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0111_alter_shop_receipt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderpayment",
            name="custormmerName",
        ),
        migrations.RemoveField(
            model_name="orderpayment",
            name="custormmerTelNo",
        ),
    ]
