# Generated by Django 4.2.13 on 2024-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0112_remove_orderpayment_custormmername_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="shop_receipt_flag",
            field=models.BooleanField(default=True, verbose_name="매장용 영수증"),
        ),
    ]
