# Generated by Django 4.2.13 on 2024-08-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0114_shop_additional_fee_time_shop_table_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoptable",
            name="fixed_category_id",
            field=models.PositiveIntegerField(default=0, verbose_name="고정 서브 카테고리"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="additional_fee_time",
            field=models.PositiveIntegerField(default=10, verbose_name="추가요금 시간"),
        ),
    ]
