# Generated by Django 4.2.13 on 2024-08-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0115_shoptable_fixed_category_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="after_payment_goods",
            field=models.PositiveBigIntegerField(null=True, verbose_name="결제후들어갈상품 ID"),
        ),
    ]
