# Generated by Django 4.2.13 on 2024-08-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0117_order_after_payment_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="additional_fee_goods",
            field=models.PositiveBigIntegerField(null=True, verbose_name="추가요금 상품 ID"),
        ),
    ]
