# Generated by Django 4.2.13 on 2024-08-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0118_goods_additional_fee_goods"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="pos_ad_video",
            field=models.FileField(
                max_length=300,
                null=True,
                upload_to="video/pos_ad/",
                verbose_name="포스광고",
            ),
        ),
    ]
