# Generated by Django 4.2.13 on 2024-08-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0119_shop_pos_ad_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="mainpos_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="mainpos_id",
            field=models.IntegerField(default=0),
        ),
    ]
