# Generated by Django 4.2.14 on 2024-08-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0120_checkout_mainpos_id_order_mainpos_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="cashReceiptApprovalNumber",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="cashReceiptcardNo",
            field=models.CharField(default="", max_length=50),
        ),
    ]
