# Generated by Django 4.2.14 on 2024-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0121_orderpayment_cashreceiptapprovalnumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderpayment",
            name="cashResceiptStatus",
            field=models.BooleanField(default=False, verbose_name="추가현금영수증여부"),
        ),
    ]
