# Generated by Django 4.2.14 on 2024-08-21 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0123_orderpayment_cashreceiptapprovaldate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderpayment",
            old_name="cashReceiptcardNo",
            new_name="cashReceiptCardNo",
        ),
    ]
