# Generated by Django 4.2.14 on 2024-08-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0125_shoptable_exit_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppersontype",
            name="weekday_goods",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_person_type_weekday",
                to="system_manage.goods",
            ),
        ),
        migrations.AddField(
            model_name="shoppersontype",
            name="weekend_goods",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shop_person_type_weekend",
                to="system_manage.goods",
            ),
        ),
    ]
