# Generated by Django 4.2.14 on 2024-08-27 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0126_shoppersontype_weekday_goods_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shoppersontype",
            name="goods",
        ),
    ]
