# Generated by Django 4.2.14 on 2024-08-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0127_remove_shoppersontype_goods"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="code",
            field=models.CharField(max_length=20, null=True, verbose_name="상품코드"),
        ),
    ]
