# Generated by Django 4.2.14 on 2024-08-27 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0129_alter_goods_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(max_length=100, null=True, verbose_name="가맹점한글명"),
                ),
                ("message", models.TextField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system_manage.shop",
                    ),
                ),
            ],
            options={
                "db_table": "sms_log",
            },
        ),
    ]
