# Generated by Django 4.2.14 on 2024-08-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0130_smslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="smslog",
            name="phone",
            field=models.CharField(max_length=30, null=True, verbose_name="전화번호"),
        ),
    ]
