# Generated by Django 4.2.14 on 2024-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0131_smslog_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="after_payment_goods",
            field=models.CharField(
                max_length=100, null=True, verbose_name="결제후들어갈상품 ID list"
            ),
        ),
    ]
