# Generated by Django 4.2.14 on 2024-09-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0132_alter_goods_after_payment_goods"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="kiosk_display",
            field=models.BooleanField(default=True, verbose_name="키오스크 표시"),
        ),
    ]
