# Generated by Django 4.2.14 on 2024-10-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0133_goods_kiosk_display"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="location_image",
            field=models.ImageField(
                max_length=300,
                null=True,
                upload_to="image/shop_location/",
                verbose_name="가맹점위치 이미지",
            ),
        ),
    ]
