# Generated by Django 4.2.14 on 2024-10-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0134_shop_location_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="tbridge",
            field=models.BooleanField(default=False, verbose_name="티브릿지 연동"),
        ),
    ]
