# Generated by Django 4.2.14 on 2024-10-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0137_agency_qr_order_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="qr_order_message",
            field=models.CharField(
                default="", max_length=200, verbose_name="qr주문 문자안내"
            ),
        ),
    ]
