# Generated by Django 4.2.14 on 2024-12-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0138_agency_qr_order_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="aligo_entry_template_code1",
            field=models.CharField(
                max_length=10, null=True, verbose_name="알리고 입장등록템플릿"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="aligo_entry_template_code2",
            field=models.CharField(max_length=10, null=True, verbose_name="알리고 호출템플릿"),
        ),
        migrations.AddField(
            model_name="shop",
            name="aligo_sender_key",
            field=models.CharField(max_length=50, null=True, verbose_name="알리고 샌더키"),
        ),
    ]
