# Generated by Django 4.2.14 on 2024-12-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0139_shop_aligo_entry_template_code1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smslog",
            name="message_type",
            field=models.CharField(
                default="0", max_length=10, verbose_name="0:문자, 1:알림톡"
            ),
        ),
    ]
