# Generated by Django 4.2.14 on 2024-12-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0140_smslog_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entryqueue",
            name="called_at",
            field=models.DateTimeField(null=True, verbose_name="마지막 호출일"),
        ),
    ]
