# Generated by Django 4.2.14 on 2025-02-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0141_entryqueue_called_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shopcoupon",
            name="coupon_type",
        ),
        migrations.RemoveField(
            model_name="shopcoupon",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="shopcoupon",
            name="discount_type",
        ),
        migrations.RemoveField(
            model_name="shopmembercoupon",
            name="coupon_type",
        ),
        migrations.RemoveField(
            model_name="shopmembercoupon",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="shopmembercoupon",
            name="discount_type",
        ),
        migrations.AddField(
            model_name="shop",
            name="coupon_flag",
            field=models.BooleanField(default=False),
        ),
    ]
