# Generated by Django 4.2.14 on 2025-03-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0143_shopmembercoupon_shop_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopmembercoupon",
            name="expiration_date",
            field=models.DateTimeField(null=True, verbose_name="만료일"),
        ),
    ]
