# Generated by Django 4.2.14 on 2025-03-19 16:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0144_alter_shopmembercoupon_expiration_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entryqueue",
            name="shop_member",
        ),
    ]
