# Generated by Django 4.2.14 on 2025-03-24 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0148_shoppos_main_tid"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="pos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system_manage.pos",
            ),
        ),
    ]
