# Generated by Django 4.2.14 on 2025-03-24 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0149_shop_pos"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoptable",
            name="pos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="system_manage.pos",
            ),
        ),
        migrations.DeleteModel(
            name="ShopPos",
        ),
    ]
