# Generated by Django 4.2.14 on 2025-03-24 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0150_shoptable_pos_delete_shoppos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoptable",
            name="pos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="system_manage.pos"
            ),
        ),
    ]
