# Generated by Django 4.2.14 on 2025-03-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0151_alter_shoptable_pos"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="shoptable",
            name="shop_table_no_unique",
        ),
        migrations.AddConstraint(
            model_name="shoptable",
            constraint=models.UniqueConstraint(
                fields=("pos", "shop", "table_no"), name="pos_shop_table_no_unique"
            ),
        ),
    ]
