# Generated by Django 4.2.14 on 2025-04-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "system_manage",
            "0153_rename_cashresceiptstatus_orderpayment_cashreceiptstatus",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="printer_port1",
            field=models.CharField(
                default="COM2", max_length=5, null=True, verbose_name="프린터 port1"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="printer_port2",
            field=models.CharField(
                default="COM3", max_length=5, null=True, verbose_name="프린터 port2"
            ),
        ),
    ]
