# Generated by Django 4.2.14 on 2025-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0154_shop_printer_port1_shop_printer_port2"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="table_paginate_by",
            field=models.PositiveIntegerField(default=50),
        ),
    ]
