# Generated by Django 4.2.14 on 2025-04-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0155_shop_table_paginate_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="printer_port1",
            field=models.CharField(
                default="COM1", max_length=5, null=True, verbose_name="프린터 port1"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="printer_port2",
            field=models.CharField(
                default="", max_length=5, null=True, verbose_name="프린터 port2"
            ),
        ),
    ]
