# Generated by Django 4.2.14 on 2025-04-29 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0156_alter_shop_printer_port1_alter_shop_printer_port2"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincategory",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="system_manage.shop",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="shop",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category",
                to="system_manage.shop",
            ),
        ),
    ]
