# Generated by Django 4.2.14 on 2025-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0157_maincategory_shop_subcategory_shop"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subcategory",
            name="main_category_name_kr_unique",
        ),
        migrations.RemoveConstraint(
            model_name="subcategory",
            name="main_category_name_en_unique",
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("shop", "main_category", "name_kr"),
                name="shop_main_category_name_kr_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="subcategory",
            constraint=models.UniqueConstraint(
                fields=("shop", "main_category", "name_en"),
                name="shop_main_category_name_en_unique",
            ),
        ),
    ]
