# Generated by Django 4.2.14 on 2025-04-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0159_alter_maincategory_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="kiosk_rank",
            field=models.PositiveIntegerField(default=0, verbose_name="키오스크 정렬 순위"),
        ),
        migrations.AddField(
            model_name="goods",
            name="pos_rank",
            field=models.PositiveIntegerField(default=0, verbose_name="포스 정렬 순위"),
        ),
    ]
