# Generated by Django 4.2.14 on 2025-05-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0160_goods_kiosk_rank_goods_pos_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="printer_baud_rate",
            field=models.PositiveIntegerField(
                default=9600, verbose_name="프린터 baud rate"
            ),
        ),
    ]
