# Generated by Django 4.2.14 on 2025-05-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0161_shop_printer_baud_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="maincategory",
            name="rank",
            field=models.PositiveIntegerField(default=0, verbose_name="정렬 순위"),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="rank",
            field=models.PositiveIntegerField(default=0, verbose_name="정렬 순위"),
        ),
    ]
