# Generated by Django 4.2.14 on 2025-07-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_manage", "0162_maincategory_rank_subcategory_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="agency",
            name="country",
            field=models.CharField(
                choices=[("KR", "Korea"), ("JP", "Japan")], default="KR", max_length=2
            ),
        ),
    ]
