# Generated by Django 4.2.14 on 2025-10-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0163_agency_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='qr_link',
            field=models.CharField(default='', max_length=300, verbose_name='qr주문 링크'),
        ),
        migrations.AddField(
            model_name='shop',
            name='qr_order_message',
            field=models.CharField(default='', max_length=200, verbose_name='qr주문 문자안내'),
        ),
    ]
