# Generated by Django 4.2.14 on 2026-07-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0164_shop_qr_link_shop_qr_order_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpayment',
            name='accountCloseDate',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='accountNo',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='applNo',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='bankCode',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='billkey',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='cardAmount',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='cardPointAmount',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='cardPointApplNo',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='couponAmount',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='customerName',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='customerTelNo',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='feeAmount',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='goodsName',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='greenDepositAmount',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='mbrNo',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='mbrRefNo',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='payType',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='pointAmount',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='refNo',
        ),
        migrations.RemoveField(
            model_name='orderpayment',
            name='taxFreeAmount',
        ),
        migrations.AlterField(
            model_name='shop',
            name='printer_baud_rate',
            field=models.PositiveIntegerField(default=115200, verbose_name='프린터 baud rate'),
        ),
    ]
