# Generated by Django 4.2.14 on 2026-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0165_remove_orderpayment_accountclosedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='approvalNumber',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
