# Generated by Django 4.2.14 on 2026-07-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0166_alter_orderpayment_approvalnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_no', models.IntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_manage.shop')),
            ],
            options={
                'db_table': 'order_sequence',
            },
        ),
        migrations.AddConstraint(
            model_name='ordersequence',
            constraint=models.UniqueConstraint(fields=('shop', 'date'), name='shop_date_unique'),
        ),
    ]
