# Generated by Django 4.2.14 on 2026-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0167_ordersequence_ordersequence_shop_date_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderpayment',
            constraint=models.UniqueConstraint(fields=('order', 'approvalNumber'), name='order_approvalNumber_unique'),
        ),
    ]
