# Generated by Django 4.2.14 on 2026-07-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_manage', '0168_orderpayment_order_approvalnumber_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receive_type',
            field=models.CharField(choices=[('0', '매장'), ('1', '픽업')], default='0', max_length=10),
        ),
    ]
